n1, n2, n3, n4, n5 = int(input()), int(input()), int(input()), int(input()), int(input())
nmax = max(n1, n2, n3, n4, n5)
nmin = min(n1, n2, n3, n4, n5)
print("Наименьшее число =", nmin)
print("Наибольшее число =", nmax)
